import { ProductItem } from './store';

export const MOCK_100ML_BOTTLES: ProductItem[] = [
  {
    id: 'bote-100ml-diamante-plata',
    sku: 'BOT-100-DIA-P',
    barcode: '741002000001',
    name: 'Bote de Vidrio 100ml Relieve Diamante - Tapa Plata',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.43,
    stock: 288,
    minStock: 25,
    imageUrl: '/images/botes/bote_100ml_diamante_plata.jpg',
    isAvailableOnline: true,
    puesto: 'B1',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-sauvage-degrade',
    sku: 'BOT-100-SAU-N',
    barcode: '741002000002',
    name: 'Bote de Vidrio 100ml Degradé Azul Noche - Tapa Negra',
    brand: 'Yahua Industrial',
    gender: 'Caballero',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.56,
    stock: 490,
    minStock: 40,
    imageUrl: '/images/botes/bote_100ml_sauvage_degrade_negro.jpg',
    isAvailableOnline: true,
    puesto: 'B1',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-acanalado-blanco',
    sku: 'BOT-100-ACA-B',
    barcode: '741002000003',
    name: 'Bote de Vidrio 100ml Acanalado - Tapa Blanca / Oro',
    brand: 'Yahua Industrial',
    gender: 'Dama',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.47,
    stock: 54,
    minStock: 10,
    imageUrl: '/images/botes/bote_100ml_acanalado_tapa_blanca.jpg',
    isAvailableOnline: true,
    puesto: 'B2',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-acanalado-negro',
    sku: 'BOT-100-ACA-N',
    barcode: '741002000004',
    name: 'Bote de Vidrio 100ml Acanalado - Tapa Negra / Oro',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.47,
    stock: 54,
    minStock: 10,
    imageUrl: '/images/botes/bote_100ml_acanalado_tapa_negra.jpg',
    isAvailableOnline: true,
    puesto: 'B2',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-cuadrado-bleu',
    sku: 'BOT-100-CUA-B',
    barcode: '741002000005',
    name: 'Bote de Vidrio 100ml Cuadrado Azul Oscuro - Tapa Negra',
    brand: 'Yahua Industrial',
    gender: 'Caballero',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.56,
    stock: 300,
    minStock: 25,
    imageUrl: '/images/botes/bote_100ml_cuadrado_bleu_negro.jpg',
    isAvailableOnline: true,
    puesto: 'B2',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-frosted-esfera-madera-clara',
    sku: 'BOT-100-FRO-EMC',
    barcode: '741002000006',
    name: 'Bote de Vidrio 100ml Esmerilado - Tapa Esfera Madera Clara',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.57,
    stock: 245,
    minStock: 20,
    imageUrl: '/images/botes/bote_100ml_frosted_esfera_madera_clara.jpg',
    isAvailableOnline: true,
    puesto: 'B3',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-frosted-esfera-madera-oscura',
    sku: 'BOT-100-FRO-EMO',
    barcode: '741002000007',
    name: 'Bote de Vidrio 100ml Esmerilado - Tapa Esfera Madera Oscura',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.57,
    stock: 245,
    minStock: 20,
    imageUrl: '/images/botes/bote_100ml_frosted_esfera_madera_oscura.jpg',
    isAvailableOnline: true,
    puesto: 'B3',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-hombro-curvo-blanco',
    sku: 'BOT-100-HC-B',
    barcode: '741002000008',
    name: 'Bote de Vidrio 100ml Cilíndrico Hombro Curvo - Tapa Blanca / Oro',
    brand: 'Yahua Industrial',
    gender: 'Dama',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.66,
    stock: 70,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_cilindrico_hombro_blanco.jpg',
    isAvailableOnline: true,
    puesto: 'B3',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-hombro-curvo-negro',
    sku: 'BOT-100-HC-N',
    barcode: '741002000009',
    name: 'Bote de Vidrio 100ml Cilíndrico Hombro Curvo - Tapa Negra / Oro',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.66,
    stock: 70,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_cilindrico_hombro_negro.jpg',
    isAvailableOnline: true,
    puesto: 'B3',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-santal-oro',
    sku: 'BOT-100-SAN-O',
    barcode: '741002000010',
    name: 'Bote de Vidrio 100ml Estilo Le Labo - Tapa Oro Moleteada',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.52,
    stock: 210,
    minStock: 20,
    imageUrl: '/images/botes/bote_100ml_santal_tapa_oro.jpg',
    isAvailableOnline: true,
    puesto: 'B4',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-cilindrico-tapa-negra',
    sku: 'BOT-100-CIL-TN',
    barcode: '741002000011',
    name: 'Bote de Vidrio 100ml Cilíndrico Cristal - Tapa Negra',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.45,
    stock: 280,
    minStock: 25,
    imageUrl: '/images/botes/bote_100ml_cilindrico_tapa_negra.jpg',
    isAvailableOnline: true,
    puesto: 'B4',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-frosted-cilindro-madera-clara',
    sku: 'BOT-100-FRO-CMC',
    barcode: '741002000012',
    name: 'Bote de Vidrio 100ml Esmerilado - Tapa Madera Clara',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.55,
    stock: 94,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_frosted_cilindro_madera_clara.jpg',
    isAvailableOnline: true,
    puesto: 'B4',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-frosted-cilindro-madera-media',
    sku: 'BOT-100-FRO-CMM',
    barcode: '741002000013',
    name: 'Bote de Vidrio 100ml Esmerilado - Tapa Madera Media Nogal',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.55,
    stock: 93,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_frosted_cilindro_madera_media.jpg',
    isAvailableOnline: true,
    puesto: 'B4',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-frosted-cilindro-madera-oscura',
    sku: 'BOT-100-FRO-CMO',
    barcode: '741002000014',
    name: 'Bote de Vidrio 100ml Esmerilado - Tapa Madera Oscura Wengué',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.55,
    stock: 93,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_frosted_cilindro_madera_oscura.jpg',
    isAvailableOnline: true,
    puesto: 'B4',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-rectangular-frosted-plata',
    sku: 'BOT-100-REC-FP',
    barcode: '741002000015',
    name: 'Bote de Vidrio 100ml Rectangular Esmerilado - Tapa Plata Mate',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.54,
    stock: 320,
    minStock: 25,
    imageUrl: '/images/botes/bote_100ml_rectangular_frosted_plata.jpg',
    isAvailableOnline: true,
    puesto: 'B5',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-chanel-cristal',
    sku: 'BOT-100-CHA-C',
    barcode: '741002000016',
    name: 'Bote de Vidrio 100ml Rectangular Clásico - Tapa Cristal Facetada',
    brand: 'Yahua Industrial',
    gender: 'Dama',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.52,
    stock: 320,
    minStock: 25,
    imageUrl: '/images/botes/bote_100ml_chanel_tapa_cristal.jpg',
    isAvailableOnline: true,
    puesto: 'B5',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-rockstud-tapa-negra',
    sku: 'BOT-100-ROC-N',
    barcode: '741002000017',
    name: 'Bote de Vidrio 100ml Rockstud Pirámides - Tapa Negra',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.48,
    stock: 150,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_rockstud_tapa_negra.jpg',
    isAvailableOnline: true,
    puesto: 'B5',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-rockstud-tapa-cobre',
    sku: 'BOT-100-ROC-C',
    barcode: '741002000018',
    name: 'Bote de Vidrio 100ml Rockstud Pirámides - Tapa Café Cobre / Oro',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.68,
    stock: 150,
    minStock: 15,
    imageUrl: '/images/botes/bote_100ml_rockstud_tapa_cobre.jpg',
    isAvailableOnline: true,
    puesto: 'B5',
    supplier: 'Yahua Industrial Co., Ltd.'
  },
  {
    id: 'bote-100ml-cilindrico-alto-negro',
    sku: 'BOT-100-CIL-AN',
    barcode: '741002000019',
    name: 'Bote de Vidrio 100ml Cilíndrico Alto - Tapa Negra Clásica',
    brand: 'Yahua Industrial',
    gender: 'Unisex',
    category: 'Botes',
    unit: 'Unidad',
    price: 0,
    cost: 0.40,
    stock: 1980,
    minStock: 100,
    imageUrl: '/images/botes/bote_100ml_cilindrico_alto_tapa_negra.jpg',
    isAvailableOnline: true,
    puesto: 'B6',
    supplier: 'Yahua Industrial Co., Ltd.'
  }
];
